### PR TITLE
fix #442: race conditions when updating PlanningScene state

### LINKED ISSUE #442: Trajectory start doesn't match Current Position, when using plan/execute
When sending back-to-back motion commands to MoveIt (using blocking calls), the trajectory start position should match (approximately) the goal position of the previous move.  This works when using the all-in-one `move()` call, but not when using separate `plan()` and `execute(plan)` calls.  In that case, it seems like the start position is using an outdated representation of the robot state, which lags behind the current robot state.

The expected behavior can be coerced using a few workarounds:
- add a delay (~1 sec) between motion requests
- explicitly force the `MotionPlanRequest` current state to the current joint position reported by MoveIt
- use the combined `move()` method instead.

I have tested this behavior using both a physical robot (Motoman FS100/SIA-20D) and a "virtual robot" (the ROS-Industrial Industrial_Robot_Simulator), under both groovy and hydro releases.
## Steps to Reproduce
1. Launch any MoveIt package.  For example:
   
   ```
   apt-get install ros-hydro-motoman ros-hydro-industrial-robot-simulator
   roslaunch motoman_sia20d_moveit_config moveit_planning_execution.launch
   ```
2. Disable any MoveIt RViz planning displays, so that only the current robot state is displayed.
3. Download the test script from [here](https://gist.github.com/JeremyZoss/63dfdf24a97c5e6e7d65)
4. Run the test script, using its default configuration
   
   ```
   ./moveit_trajStart.py
   ```
5. Observe the odd RViz motion and reported error messages.  See below for a more detailed explanation.
## Test Script Explanation

The test script creates a sequence of joint positions, using fixed-offsets from the current robot position.  It's easiest to observe what's happening if the robot starts in a "clean" position (all-zeros, or similar).  The script then executes a move to each of the positions, using blocking `plan` and `execute(plan)` calls.  The planned trajectory is compared against both the `current_joint_values` (as reported by MoveIt) and the target goal position, to verify the start/end positions.  If the values differ, an error message is reported.

Here is a sample of the reported planning error:

```
    curPos  : [0.200006, 0.199941, 0.200077, 0.200019, 0.200077, 0.200019, 0.200097]
    traj[0] : [0.015490, 0.015486, 0.015490, 0.015488, 0.015494, 0.015491, 0.015492]
    delta   : [-0.184516, -0.184455, -0.184587, -0.184531, -0.184583, -0.184528, -0.184604]
```

The correct behavior is for the script to execute cleanly, with no reported trajectory validation errors.  The observed behavior is that the start position does not match the current position reported by MoveIt.
## Experimentation

To further experiment with this issue, you can try the following things:
- pass a numeric argument to the script to adjust the delay between motion commands.  A delay of 1 sec will allow clean execution: `./moveit_trajStart.py 1.0`
- uncomment the script line `set_start_state`, to explicitly force the start state in the `MotionPlanRequest` to match the reported current state.
- comment the `plan()`, `validate_plan()`, and `execute()` lines, and uncomment the `go()` line.

### PR DESCRIPTION
**Pull request by rhaschke**
This wip branch is intended as joint collaboration branch to fix the race conditions in scene updates reported in #442. All developers are invited to contribute via additional PRs. I'm trying to centralize the discussion on this issue here.

Related PRs:
- #442 (reported issue)
- #671 (active waiting work-around)
- #686 (synchronous update work-around).

As pointed out in a [comment of #671](https://github.com/ros-planning/moveit_ros/pull/671#issuecomment-232843090) the fundamental underlying reason might be that scene update messages pile up in the callback queue (due to sequential processing by a single spinner thread). Hence, not only pending joint state updates may be missed, but also other scene updates.
Hence I suggest to modify `planning_scene_monitor::LockedPlanningSceneRO` such that it waits until all scene updates with `timestamp < ros::Time::now()` are processed and only then returns the current planning scene. Only this will ensure, that all pending scene updates are considered at a given time.

Proposed concrete changes:
- Have an own CallbackQueue and AsyncSpinner for a PlanningSceneMonitor (PSM) instance. This might conflict with #701.
- Handle the actual _incoming_ timestamps of planning scene updates. Currently, the throttling is performed [based on current timestamps](https://github.com/ros-planning/moveit_ros/blob/indigo-devel/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L1133).
- As this will conflict with throttling of (state) updates (requesting a LockedPlanningSceneRO will enforce to consider all pending updates), we need another mechanism for throttling. Essentially we have two use cases: 1. Another thread within move_group needs to read the current state and wants to ensure to get all pending updates. 2. The PSM regularly should publishes scene updates. If there are no other accesses to the PSM in between, there is no reason to perform state updates in between.

Before starting along that route, I'm waiting for positive feedback from some developers. And of course, I hope for active contributions. Please announce before you start to tackle a sub task.

### CODE REVIEW

**Comment by davetcoleman** [comment]
I don't use the Rviz plugin and don't run into these race conditions in my normal preferred workflow so don't fully understand the details at play here, but I'm glad you are tackling this. Hopefully @v4hn can help. Perhaps @jbohren has some insight since he's improved MoveIt! race conditions in the past. I'll continue to do high-level reviews.

**Comment by rhaschke** [comment]
Proof-of-concept implementation on top of #713.
Needs code cleanup! Please don't complain (yet) on code style ;-)

**Comment by rhaschke** [comment]
@v4hn I cleaned up the commit history. Please review now.
I do now get an exception on destroying a static mutex when closing rviz. Cannot yet tell, where this comes from. Seems to be related to unloading of a (static?) CollisionPlugin.

**Comment by rhaschke** [comment]
TODOs:
Check python interface. Can we go without sleeps now?
Check current state before executing trajectory: Is initial trajectory point == current state?

**Comment by rhaschke** [comment]
Python API works without sleeps like a charm.
Added state validity check to MoveGroup interface.
ABI compatibility by moving new class members to the end of the struct.
Ready to merge.

**Comment by davetcoleman** [comment]
Can you rename the subject of the PR to something more descriptive than work-in-progress for future reference? and so to ensure its ready for merging ;-)

**Comment by davetcoleman** [comment]
Also, with 8 commits in this PR its my experience that reviewers request they be merged into fewer (preferably 1).

File: planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h [hunk 1]
```diff
@@ -514,6 +517,11 @@ class PlanningSceneMonitor : private boost::noncopyable
 
   class DynamicReconfigureImpl;
   DynamicReconfigureImpl *reconfigure_impl_;
+
+  ros::CallbackQueue                    callback_queue_;
+  boost::scoped_ptr<ros::AsyncSpinner>  spinner_;
+  ros::Time                             last_robot_motion_time_; /// Last time the robot has moved
+  bool                                  enforce_next_state_update_;
```
Comment (davetcoleman) [inline planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h:524]: its out of style to suddenly start aligning variable names, but I guess its not a big deal

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 2]
```diff
@@ -808,6 +819,32 @@ void planning_scene_monitor::PlanningSceneMonitor::currentWorldObjectUpdateCallb
...
+{
+  if (t.isZero())
+    return;
+
+  enforce_next_state_update_ = true; // enforce next state update to trigger without throttling
+
+  // Robot state updates in the scene are only triggered by the state monitor on changes of the state.
+  // Hence, last_state_update_time_ might be much older than current_state_monitor_ (when robot didn't moved for a while).
+  boost::shared_lock<boost::shared_mutex> lock(scene_update_mutex_);
+  ros::Time robot = current_state_monitor_ ? current_state_monitor_->getCurrentStateTime() : ros::Time();
```
Comment (davetcoleman) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp]: `robot` as a time variable seems inaptly named

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 3]
```diff
@@ -808,6 +819,32 @@ void planning_scene_monitor::PlanningSceneMonitor::currentWorldObjectUpdateCallb
...
+  while (current_state_monitor_ && // sanity check
+         robot < t && // wait for recent state update
+         (t - last_robot_motion_time_).toSec() < 1.0) // but only if robot moved in last second
+  {
+    new_scene_update_condition_.wait_for(lock, boost::chrono::milliseconds(50));
+    robot=current_state_monitor_->getCurrentStateTime();
```
Comment (davetcoleman) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp]: spaces around =

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 4]
```diff
@@ -808,6 +819,32 @@ void planning_scene_monitor::PlanningSceneMonitor::currentWorldObjectUpdateCallb
...
+  }
+  // Now, we know that robot state is up-to-date
+
+  // ensure that last update time is more recent than t (or no more update events pending)
+  while (last_update_time_ < t && !callback_queue_.empty()) {
```
Comment (davetcoleman) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp]: line break for {

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 5]
```diff
@@ -817,23 +854,24 @@ void planning_scene_monitor::PlanningSceneMonitor::lockSceneRead()
...
 {
-  scene_update_mutex_.unlock_shared();
   if (octomap_monitor_)
     octomap_monitor_->getOcTreePtr()->unlockRead();
+  scene_update_mutex_.unlock_shared();
 }
 
 void planning_scene_monitor::PlanningSceneMonitor::lockSceneWrite()
 {
+  ros::WallTime t = ros::WallTime::now();
```
Comment (davetcoleman) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp]: unused var

File: planning_interface/move_group_interface/src/move_group.cpp [hunk 6]
```diff
@@ -689,6 +689,31 @@ class MoveGroup::MoveGroupImpl
...
+  {
+    robot_state::RobotStatePtr current_state;
+    if (!getCurrentState(current_state))
+        return false;
+    if (plan.trajectory_.joint_trajectory.points.empty())
+        return true;
+
+    const trajectory_msgs::JointTrajectory &trajectory = plan.trajectory_.joint_trajectory;
+    const std::vector<double> &positions = trajectory.points.front().positions;
+    size_t n = trajectory.joint_names.size();
```
Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: std::

Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: also check that joint_names is not empty?

File: planning_interface/move_group_interface/src/move_group.cpp [hunk 7]
```diff
@@ -689,6 +689,31 @@ class MoveGroup::MoveGroupImpl
...
+    if (positions.size() != n)
+        return false;
+
+    for (size_t i=0; i < n; ++i)
```
Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: std::

Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: spaces around =

File: planning_interface/move_group_interface/src/move_group.cpp [hunk 8]
```diff
@@ -689,6 +689,31 @@ class MoveGroup::MoveGroupImpl
...
+    {
+      const robot_model::JointModel* jm = robot_model_->getJointModel(trajectory.joint_names[i]);
+      if (!jm)
+        continue;
```
Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: seems like an error should be thrown if not JointModel exists

File: planning_interface/move_group_interface/src/move_group.cpp [hunk 9]
```diff
@@ -689,6 +689,31 @@ class MoveGroup::MoveGroupImpl
...
+      if (current_state->getJointPositions(jm)[0] != positions[i])
```
Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: Add TODO note here that this only supports JointModels with one active joint

Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: also this should check that it is within machine epsilon

File: visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp [hunk 10]
```diff
@@ -139,7 +139,9 @@ void MotionPlanningFrame::computeExecuteButtonClicked()
   if (move_group_ && current_plan_)
   {
     ui_->stop_button->setEnabled(true); // enable stopping
-    bool success = move_group_->execute(*current_plan_);
+    bool success =
+      move_group_->validatePlan(*current_plan_) &&
```
Comment (davetcoleman) [inline visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp:143]: instead of chaining these, i think it would be much nicer to have a console output explaining why validatePlan failed

File: planning_interface/move_group_interface/src/move_group.cpp (hunk 7 above)
Comment (rhaschke) [inline planning_interface/move_group_interface/src/move_group.cpp]: Could you be more verbose, please. Would do you mean by std::? Where is it missing?

File: visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp (hunk 10 above)
Comment (rhaschke) [inline visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp:143]: Added the console output in validatePlan().

**Comment by rhaschke** [comment]
Addressed @davetcoleman's codeing style comments.
I would like to keep the large number (8) of commits, because each of them has a clearly separeted semantics and could be use to roll back individual parts. At least I carefully designed those commits when cleaning up.
Before final merging, I will cleanup the new fixup commits. Simply give me a go, if you are happy and I will do the final merge (as well as cherry-pick to jade and kinetic).

File: planning_interface/move_group_interface/src/move_group.cpp (hunk 6 above)
Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: moveit uses `std::size_t` thousands of times throughout its code base, so we should stick to that. i now see there is plenty of strong opinions on `std::size_t vs size_t` but I think if we were to switch you should do so in one big grep

File: planning_interface/move_group_interface/src/move_group.cpp (hunk 7 above)
Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: see previous comment

File: planning_interface/move_group_interface/src/move_group.cpp [hunk 11]
```diff
@@ -689,6 +689,38 @@ class MoveGroup::MoveGroupImpl
...
+      const robot_model::JointModel *jm = robot_model_->getJointModel(trajectory.joint_names[i]);
+      if (!jm)
+      {
+        ROS_ERROR("unknown joint in trajectory: %s", trajectory.joint_names[i]);
+        return false;
+      }
+      // TODO: check multi-DoF joints
+      if (fabs(current_state->getJointPositions(jm)[0] - positions[i]) < FLT_EPSILON)
+      {
+        ROS_ERROR("trajectory start deviates from current robot state");
```
Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: All ROS_ERROR messages are capitalized in moveit_ros, we should stick to that

File: planning_interface/move_group_interface/src/move_group.cpp [hunk 12]
```diff
@@ -689,6 +689,38 @@ class MoveGroup::MoveGroupImpl
...
+    for (size_t i = 0; i < n; ++i)
+    {
+      const robot_model::JointModel *jm = robot_model_->getJointModel(trajectory.joint_names[i]);
+      if (!jm)
+      {
+        ROS_ERROR("unknown joint in trajectory: %s", trajectory.joint_names[i]);
+        return false;
+      }
+      // TODO: check multi-DoF joints
+      if (fabs(current_state->getJointPositions(jm)[0] - positions[i]) < FLT_EPSILON)
```
Comment (davetcoleman) [inline planning_interface/move_group_interface/src/move_group.cpp]: moveit uses `std::numeric_limits<double>::epsilon()` throughout, and not the C equivalent

**Comment by davetcoleman** [comment]
No problem if the commits have actual purpose and are not simply incremental changes

Sorry for all the pickiness in my reviews, but most of my coding style was learned from MoveIt! so I easily see discrepancies.  And @isucan would have made the same comments because he used to for my PRs :)

Thanks!

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 13]
```diff
@@ -808,6 +819,34 @@ void planning_scene_monitor::PlanningSceneMonitor::currentWorldObjectUpdateCallb
...
+void planning_scene_monitor::PlanningSceneMonitor::syncSceneUpdates(const ros::Time &t)
+{
+  if (t.isZero())
+    return;
+
+  enforce_next_state_update_ = true;  // enforce next state update to trigger without throttling
+
+  // Robot state updates in the scene are only triggered by the state monitor on changes of the state.
+  // Hence, last_state_update_time_ might be much older than current_state_monitor_ (when robot didn't moved for a
+  // while).
```
Comment (davetcoleman) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp]: nice commenting throughout!

**Comment by v4hn** [comment]
gnarf... you're too hasty.
I was reading that request right now.

**Comment by rhaschke** [comment]
@v4hn: I want to progress ;-)

I also force-pushed a new version of the branch [`cherry-picking-716-717`](/ros-planning/moveit_ros/tree/cherry-picking-716-717) to let [Travis do its work](https://travis-ci.org/ros-planning/moveit_ros/builds/146143997).
If they are no complaints, I will fast-forward `jade-devel` to that branch and finally merge this into `kinetic-devel` later this evening.

**Comment by davetcoleman** [comment]
@rhaschke do not merge your own PRs, especially if no one in this discussion thread ever gave you a `+1`. This rule has been in place for years now. I appreciate you addressing all my feedback and there wasn't anything else I would have wanted changed, but @v4hn was [in progress](https://github.com/ros-planning/moveit_ros/pull/716#issuecomment-233989178) reviewing this PR when you merged it without his approval. Also, in [this comment](https://github.com/ros-planning/moveit_ros/pull/716#issuecomment-233096583) above I said I wanted someone else to review this because "I don't fully understand the details at play here". 

In the past it has taken _months_ to get PRs merged, to my great frustration, and I'm glad things are moving faster now, but you didn't say "Please review now" until [3 days ago](https://github.com/ros-planning/moveit_ros/pull/716#issuecomment-233454647) so don't rush things too much. I've been daily reviewing this PR.

Anyway, thanks for all these great improvements and bug fixes!

**Comment by rhaschke** [comment]
@davetcoleman You are right. I was too hasty.
@v4hn Did you had any comments to the content of the PR? If so, please post them, even if the core of the source is already pushed. There are two cherry-pick branches pending (for jade and kinetic) and I'm definitely awaiting your feedback before creating final PRs for them.

**Comment by v4hn** [comment]
The reason why I didn't review this request in the last few days is simply because I didn't have the time.
This is nothing as trivial as adding missing dependencies, and I didn't get around to look at it yet.

I'll try to read through the whole request tomorrow and post feedback.

@rhaschke: Thanks for all your work!

File: planning_interface/move_group_interface/src/move_group.cpp [hunk 14]
```diff
@@ -689,6 +689,38 @@ class MoveGroup::MoveGroupImpl
...
+    for (std::size_t i = 0; i < n; ++i)
+    {
+      const robot_model::JointModel *jm = robot_model_->getJointModel(trajectory.joint_names[i]);
+      if (!jm)
+      {
+        ROS_ERROR_STREAM("Unknown joint in trajectory: " << trajectory.joint_names[i]);
+        return false;
+      }
+      // TODO: check multi-DoF joints
+      if (fabs(current_state->getJointPositions(jm)[0] - positions[i]) < std::numeric_limits<float>::epsilon())
```
Comment (rhaschke) [inline planning_interface/move_group_interface/src/move_group.cpp:715]: Switching to the machine epsilon check, I inserted a new bug: 
The comparison operator needs to be inversed.

**Comment by rhaschke** [comment]
@v4hn Playing around with the [new fake controllers](/ros-planning/moveit_plugins/pull/21), I noticed another open issue: 
The last scene update is not always received in time while waiting for PlanningScene synchronization.

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 15]
```diff
@@ -163,6 +165,11 @@ void planning_scene_monitor::PlanningSceneMonitor::initialize(const planning_sce
   moveit::tools::Profiler::ScopedStart prof_start;
   moveit::tools::Profiler::ScopedBlock prof_block("PlanningSceneMonitor::initialize");
 
+  // start our own spinner listening on our own callback_queue to become independent of any global callback queue
+  root_nh_.setCallbackQueue(&callback_queue_);
+  spinner_.reset(new ros::AsyncSpinner(1 /* threads */, &callback_queue_));
+  spinner_->start();
```
Comment (v4hn) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:171]: @alainsanguinetti Could you have a look at this commit w.r.t. your pull-request #701?
Starting a spinner in the monitor obviously takes control out of the user's hands again.
Even so, afaics the PlanningSceneMonitor always used the global callback queue, right?
I don't see a way to provide the nodehandles the psm uses...

I suppose at least we should provide the user with a way to override the control flow from the outside.
tf/tf2 implement a similar scheme and they use an optional parameter `spin_thread` in the constructor, but this breaks ABI.
Is it enough to add the optional parameter in kinetic and leave indigo with the background thread?

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 16]
```diff
@@ -213,8 +220,8 @@ void planning_scene_monitor::PlanningSceneMonitor::initialize(const planning_sce
   publish_planning_scene_frequency_ = 2.0;
   new_scene_update_ = UPDATE_NONE;
 
-  last_update_time_ = ros::Time::now();
-  last_state_update_ = ros::WallTime::now();
+  last_update_time_ = last_robot_motion_time_ = ros::Time::now();
+  wall_last_state_update_ = ros::WallTime::now();
```
Comment (v4hn) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:224]: shouldn't all of these be initialized with `Time(0)`?
At this point we didn't receive anything yet, so I wouldn't claim that we just "updated".

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 17]
```diff
@@ -358,6 +366,8 @@ void planning_scene_monitor::PlanningSceneMonitor::scenePublishingThread()
             if (octomap_monitor_) lock = octomap_monitor_->getOcTreePtr()->reading();
             scene_->getPlanningSceneMsg(msg);
           }
+          // also publish timestamp of this robot_state
+          msg.robot_state.joint_state.header.stamp = last_robot_motion_time_;
```
Comment (v4hn) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:370]: nice catch!
I consider it quite a shortcoming that MoveIt! does rarely consider time stamps..

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 18]
```diff
@@ -808,6 +820,41 @@ void planning_scene_monitor::PlanningSceneMonitor::currentWorldObjectUpdateCallb
...
+  ROS_DEBUG_STREAM_NAMED("PSM", "sync to: " << fmod(t.toSec(), 10.));
+  enforce_next_state_update_ = true;  // enforce next state update to trigger without throttling
+
+  // Robot state updates in the scene are only triggered by the state monitor on changes of the state.
+  // Hence, last_state_update_time_ might be much older than current_state_monitor_ (when robot didn't moved for a while).
+  boost::shared_lock<boost::shared_mutex> lock(scene_update_mutex_);
+  ros::Time last_robot_update = current_state_monitor_ ? current_state_monitor_->getCurrentStateTime() : ros::Time();
+  while (current_state_monitor_ &&                     // sanity check
+         last_robot_update < t &&                      // wait for recent state update
+         (t - last_robot_motion_time_).toSec() < 1.0)  // but only if robot moved in last second
```
Comment (v4hn) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:835]: What? :-1: on the magic 1.0s .
Why did you add that last condition? It seems to be superfluous and error-prone to me.

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp (hunk 16 above)
Comment (rhaschke) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:224]: I also thought about this, but then decided to keep the previous semantics.

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 19]
```diff
@@ -979,7 +1027,7 @@ void planning_scene_monitor::PlanningSceneMonitor::startStateMonitor(const std::
   if (scene_)
   {
     if (!current_state_monitor_)
-      current_state_monitor_.reset(new CurrentStateMonitor(getRobotModel(), tf_));
+      current_state_monitor_.reset(new CurrentStateMonitor(getRobotModel(), tf_, root_nh_));
```
Comment (v4hn) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:1020]: Nice use-case for the new constructor! :-)

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 20]
```diff
@@ -808,6 +820,41 @@ void planning_scene_monitor::PlanningSceneMonitor::currentWorldObjectUpdateCallb
...
+  // Hence, last_state_update_time_ might be much older than current_state_monitor_ (when robot didn't moved for a while).
+  boost::shared_lock<boost::shared_mutex> lock(scene_update_mutex_);
+  ros::Time last_robot_update = current_state_monitor_ ? current_state_monitor_->getCurrentStateTime() : ros::Time();
+  while (current_state_monitor_ &&                     // sanity check
+         last_robot_update < t &&                      // wait for recent state update
+         (t - last_robot_motion_time_).toSec() < 1.0)  // but only if robot moved in last second
+  {
+    ROS_DEBUG_STREAM_NAMED("PSM", "robot monitor update " << (t-robot).toSec() << " ago"
+                           << " robot state update " << (t-last_robot_motion_time_).toSec() << "ago");
+    new_scene_update_condition_.wait_for(lock, boost::chrono::milliseconds(50));
```
Comment (v4hn) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:837]: Technically it doesn't really make sense to wait using the scene update condition variable,
because we are only interested in joint state updates here.
But then it probably doesn't make much of a difference..

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp (hunk 18 above)
Comment (rhaschke) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:835]: It's highly important! I was hoping, the comment explains it. I'll try again:

This was only relevant on rviz, which uses a PSM without a robot state monitor. Hence rviz receives it's scene updates via planning scene diffs from `move_group`'s PSM that actually monitors the robot state. However, publishing scene diffs is [throttled in PSM](https://github.com/ros-planning/moveit_ros/blob/9596574fcabd8dd4c6e0603a054138f8b2ec924a/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L382), which means that rviz' PSM should wait for a while until move_group's PSM has definitely published an update.

Actually, one second seems even too short, as the default rate is [`2Hz`](https://github.com/ros-planning/moveit_ros/blob/9596574fcabd8dd4c6e0603a054138f8b2ec924a/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L220). The actual value isn't really important. As soon as an update is received, the conditioned wait finishes.

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp (hunk 20 above)
Comment (rhaschke) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:837]: Only when the scene update (triggered by a state update) is finished, the update is actually incorporated into the planning scene. I'm not only attempting to sync the joint state, but also all other scene updates.

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 21]
```diff
@@ -808,6 +820,41 @@ void planning_scene_monitor::PlanningSceneMonitor::currentWorldObjectUpdateCallb
     }
 }
 
+void planning_scene_monitor::PlanningSceneMonitor::syncSceneUpdates(const ros::Time &t)
+{
+  if (t.isZero())
+    return;
+
+  ROS_DEBUG_STREAM_NAMED("PSM", "sync to: " << fmod(t.toSec(), 10.));
+  enforce_next_state_update_ = true;  // enforce next state update to trigger without throttling
```
Comment (v4hn) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:827]: @rhaschke Could you please elaborate a bit on the use of that flag-variable?
Afaics, the way this is currently used it only enforces _one_ unthrottled update of the robot state, that is triggered by the next joint state message that arrives.
However, if that message is still not the one we are waiting for, the next updates are throttled again, is that correct?
If it is, then why?

File: move_group/src/default_capabilities/execute_service_capability.cpp [hunk 22]
```diff
@@ -76,6 +76,8 @@ bool move_group::MoveGroupExecuteService::executeTrajectoryService(moveit_msgs::
         res.error_code.val = moveit_msgs::MoveItErrorCodes::TIMED_OUT;
       else
         res.error_code.val = moveit_msgs::MoveItErrorCodes::CONTROL_FAILED;
+      // wait for all planning scene updates to be processed
+      context_->planning_scene_monitor_->syncSceneUpdates();
```
Comment (v4hn) [inline move_group/src/default_capabilities/execute_service_capability.cpp:80]: I don't see any reason to sync the scene here. Did you have a something use-case in mind?

File: planning/plan_execution/src/plan_execution.cpp [hunk 23]
```diff
@@ -457,6 +457,8 @@ void plan_execution::PlanExecution::planningSceneUpdatedCallback(const planning_
 
 void plan_execution::PlanExecution::doneWithTrajectoryExecution(const moveit_controller_manager::ExecutionStatus &status)
 {
+  // sync all planning scene updates before continuing
+  planning_scene_monitor_->syncSceneUpdates();
```
Comment (v4hn) [inline planning/plan_execution/src/plan_execution.cpp:461]: Same here, I do not see a reason to wait for scene updates after we executed a trajectory.

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp (hunk 21 above)
Comment (rhaschke) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:827]: Nice catch! Actually the variable isn't really necessary anymore with the latest patches.
It was meant to quickly forward a state update to `syncUpdates()` to minimize waiting.
But, yes, indeed the variable should be reset to true in syncUpdates's while loop to keep that effect. However, I suggest to remove it.

File: planning/plan_execution/src/plan_execution.cpp (hunk 23 above)
Comment (rhaschke) [inline planning/plan_execution/src/plan_execution.cpp:461]: It's important to sync the scene state after execution to allow proper continuation with further planning steps. I'm not sure, whether I catched all places, where planning starts and thus should sync the scene state.

File: planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h [hunk 24]
```diff
@@ -411,14 +411,9 @@ class PlanningSceneMonitor : private boost::noncopyable
   planning_scene::PlanningSceneConstPtr scene_const_;
   planning_scene::PlanningScenePtr      parent_scene_; /// if diffs are monitored, this is the pointer to the parent scene
   boost::shared_mutex                   scene_update_mutex_; /// mutex for stored scene
-  ros::Time                             last_update_time_; /// Last time the scene was updated
-  ros::Time                             last_robot_motion_time_; /// Last time the robot has moved
-  bool                                  enforce_next_state_update_;
```
Comment (v4hn) [inline planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h:414]: The commit message makes it sound as if this makes the change ABI compatible.
Clearly, it does not. Overall, you added 4 members and renamed one.
Changing the size of a class is ABI breaking, and there's no way around it to fix this issue.
I agree with the idea of the request, but I want to stress the point that we have to send a notification on that change to moveit-users and likely also ros-users once this is released.

File: move_group/src/default_capabilities/move_action_capability.cpp [hunk 25]
```diff
@@ -61,7 +61,6 @@ void move_group::MoveGroupMoveAction::initialize()
 void move_group::MoveGroupMoveAction::executeMoveCallback(const moveit_msgs::MoveGroupGoalConstPtr& goal)
 {
   setMoveState(PLANNING);
-  context_->planning_scene_monitor_->updateFrameTransforms();
```
Comment (v4hn) [inline move_group/src/default_capabilities/move_action_capability.cpp:64]: As far as I can see, this is still required.
The reason this is in there is that the `MoveGroupGoal` might contain a PlanningScene in `goal->planning_options.planning_scene_diff` and attached objects in the `RobotState` components.
These are given w.r.t. frames that might have to be transformed.
However, frame updates are done in all **_but**_ the PlanningScene callback (for performance reasons).
Thus I don't see how frame updates are taken care of by `syncSceneUpdates` (which I suspect is the reason you removed it).

File: visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp [hunk 26]
```diff
@@ -402,6 +403,7 @@ void MotionPlanningFrame::remoteUpdateStartStateCallback(const std_msgs::EmptyCo
 {
   if (move_group_ && planning_display_)
   {
+    planning_display_->syncSceneUpdates();
     robot_state::RobotState state = *planning_display_->getQueryStartState();
```
Comment (v4hn) [inline visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp:409]: I would propose to move the sync down by one line (in both cases) to make it clear that the sync is because of `getPlanningSceneRO` and not because of `getQueryStartState`.
Also, this `getQueryStartState()` call seems to be totally superfluous to me. Maybe we could remove them too?

File: move_group/src/default_capabilities/move_action_capability.cpp [hunk 27]
```diff
@@ -94,6 +93,7 @@ void move_group::MoveGroupMoveAction::executeMoveCallback_PlanAndExecute(const m
 
   if (planning_scene::PlanningScene::isEmpty(goal->planning_options.planning_scene_diff))
   {
+    context_->planning_scene_monitor_->syncSceneUpdates();
```
Comment (v4hn) [inline move_group/src/default_capabilities/move_action_capability.cpp:96]: The `isEmpty` above is likely true, so this will block the callback most of the time.
I would propose to move the sync before the isEmpty check in order to avoid potential "works if `planning_scene_diff` is empty, but not if I add an object there" issues.
The following code requires the current state anyway as begin state.

File: move_group/src/default_capabilities/move_action_capability.cpp [hunk 28]
```diff
@@ -141,6 +141,7 @@ void move_group::MoveGroupMoveAction::executeMoveCallback_PlanOnly(const moveit_
 {
   ROS_INFO("Planning request received for MoveGroup action. Forwarding to planning pipeline.");
 
+  context_->planning_scene_monitor_->syncSceneUpdates();
```
Comment (v4hn) [inline move_group/src/default_capabilities/move_action_capability.cpp:144]: I believe we only have to sync here if `goal->request.start_state` is empty.
Otherwise we would sync our robot state even if we plan with totally unrelated start state.

File: planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h (hunk 24 above)
Comment (rhaschke) [inline planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h:414]: I thought that adding new members in the end is possible, isn't it? This individual commit moves all new members to the end. The renamed last_state_update_ variable is private and thus cannot be used from outside. Shouldn't that make it ABI-compatible?

File: move_group/src/default_capabilities/move_action_capability.cpp [hunk 29]
```diff
@@ -169,7 +170,6 @@ bool move_group::MoveGroupMoveAction::planUsingPlanningPipeline(const planning_i
 {
   setMoveState(PLANNING);
 
-  planning_scene_monitor::LockedPlanningSceneRO lscene(plan.planning_scene_monitor_);
```
Comment (v4hn) [inline move_group/src/default_capabilities/move_action_capability.cpp:172]: Are you sure this is not needed?
@isucan added that code in 45067d4d in 2013 and it wasn't mentioned anywhere in the function back then either...

Comment (rhaschke) [inline move_group/src/default_capabilities/move_action_capability.cpp:172]: Right, probably, this should have been removed.

File: move_group/src/default_capabilities/move_action_capability.cpp (hunk 28 above)
Comment (rhaschke) [inline move_group/src/default_capabilities/move_action_capability.cpp:144]: If only the robot state would be considered, yes.
However, I want to ensure that the whole scene with collision objects etc. is up-to-date.

File: move_group/src/default_capabilities/move_action_capability.cpp (hunk 27 above)
Comment (rhaschke) [inline move_group/src/default_capabilities/move_action_capability.cpp:96]: I cannot follow you on this. Could you explain in more detail?
When distributing `syncSceneUpdates()` throughout the code, I mainly looked for instances of `LockedPlanningSceneRO`, which indicated existing use of a (hopefully up-to-date) planning scene.

File: visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp (hunk 26 above)
Comment (rhaschke) [inline visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp:409]: Yep, indeed.

**Comment by rhaschke** [comment]
@v4hn thanks for careful reviewing. I addressed - hopefully all - your comments in #724.

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp (hunk 18 above)
Comment (v4hn) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:835]: I'm sorry, but I do not see how "but only if robot moved in last second" relates
to the PSM having to wait for scene updates.

Isn't the failure then that we don't update last_robot_update from RobotStates received in PlanningScene messages?

> -  ros::Time last_robot_update = current_state_monitor_ ? current_state_monitor_->getCurrentStateTime() : ros::Time();

To me, using `ros::Time()`, i.e. zero, for last_robot_update when no state monitor is in use seems to be the actual problem.

File: planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h (hunk 24 above)
Comment (v4hn) [inline planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h:414]: On Thu, Jul 21, 2016 at 04:13:47PM -0700, Robert Haschke wrote:

> I thought that adding new members in the end is possible, isn't it?
> This individual commit moves all new members to the end.

No it is not.
If you append new members at the end this keeps the current class layout valid,
so thus code that uses only the already existing variables of given class instances
does not break.

But still, old code that allocates instances of the class does not allocate space
for the new members. As we do not provide a factory for the PSM, we don't encapsulate
allocation in the library. So if you access the new members in the library when the
PSM was created by user-code, this _might_ segfault.

The other issue with extending classes is layout-change in the arguments of function calls
or other classes. So if anyone passes a PSM as a function parameter (that is not the last one)
or uses a PSM without a pointer as a member of a class, this will break.

> Which member is renamed? Did I missed something?

You renamed `last_state_update` to `wall_last_state_update`

v4hn

File: move_group/src/default_capabilities/move_action_capability.cpp (hunk 27 above)
Comment (v4hn) [inline move_group/src/default_capabilities/move_action_capability.cpp:96]: On Thu, Jul 21, 2016 at 05:47:12PM -0700, Robert Haschke wrote:

> When distributing `syncSceneUpdates()` throughout the code, I mainly looked for instances of `LockedPlanningSceneRO`, which indicated existing use of a (hopefully up-to-date) planning scene.

This is not enough! The PSM has a (unsafe) `getPlanningScene` method that is used in a number of places.
I would propose to explicitly sync only in very few places in order to reduce further slow-down.
- right in the beginning of all interfaces that are used to Plan or Plan and Execute and allow (or dictate) to specify an empty start state.
  We need this to ensure the interfaces really use the _current_ state.
- in the beginning of interfaces to execute a trajectory, if we want to validate the trajectory begins at the current state.

Do we need to know the _current_ robot-state anywhere else?

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp (hunk 15 above)
Comment (alainsanguinetti) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:171]: I think this is probably a nice fix. Maybe we should allow the user to specify how many threads he wants to use.
The user does not really see more than this since it is encapsulated in the move_group node, so it is probably more a matter of how many more threads does he allow on his computer.

Comment (v4hn) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:171]: On Wed, Aug 10, 2016 at 08:59:31PM -0700, Alain Sanguinetti wrote:

> I think this is probably a nice fix.

I see two problems with this:
- It should definitely be optional(enabled by default) because some people _do not want_ to have unmanaged threads running on their systems.
  See your very own request https://github.com/ros-planning/moveit_ros/pull/701 for a recent example.
- For unclear reasons it has been explicitly disallowed to start ASyncSpinner's for different threads. See https://github.com/ros/ros_comm/issues/277
  The commits in question are definitely faulty, but we are unsure about the details at the moment.
  As a result this approach will break any code that instantiates a PlanningSceneMonitor in one thread and an(other) `AsyncSpinner` in a different thread.
  One example for this is RViz.
  
  An ugly workaround to this, that had been used in other places in MoveIt, is to require (without checking) a running `AsyncSpinner` in the background
  when certain functions are called. See https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h#L619
  If the bug in ros_comm would get fixed (also in indigo), we could remove that workaround.

> Maybe we should allow the user to specify how many threads he wants to use.

I would prefer to have it fully optional. If, as an alternative, the user could specify a `NodeHandle` for which he guarantees
that it will receive asyncronous updates this would include your use-case.
