### PR TITLE
perception: adding locks to planning scene monitor (RAII version)

### LINKED ISSUE #291: move_group crashing occassionally
This happens when it is using the depth map updater. Here's a backtrace:
#0  0x00007ffff2cdd430 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#1  0x00007ffff2cdd50b in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#2  0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#3  0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#4  0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#5  0x00007ffff2cdd50b in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.s---Type <return> to continue, or q <return> to quit---
o
#6  0x00007ffff2cdd50b in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#7  0x00007ffff2cdd565 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#8  0x00007ffff2cdd550 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#9  0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#10 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#11 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

---Type <return> to continue, or q <return> to quit---
   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#12 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#13 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#14 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#15 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#16 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#17 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostrea---Type <return> to continue, or q <return> to quit---

m&) const ()
   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#18 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#19 0x00007ffff2cdd5bc in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#20 0x00007ffff2cdd612 in octomap::OcTreeBaseImpl<octomap::OcTreeNode, octomap::AbstractOccupancyOcTree>::writeData(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#21 0x00007ffff2cbe70e in planning_scene::PlanningScene::getPlanningSceneMsgOctomap(moveit_msgs::PlanningScene_std::allocator<void >&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#22 0x00007ffff2cc83cd in planning_scene::PlanningScene::getPlanningSceneDiffMsg(moveit_msgs::PlanningScene_std::allocator<void >&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
---Type <return> to continue, or q <return> to quit---
#23 0x00007ffff6937747 in planning_scene_monitor::PlanningSceneMonitor::scenePublishingThread() ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene_monitor.so
#24 0x00007ffff44bdce9 in thread_proxy ()

   from /usr/lib/libboost_thread.so.1.46.1
#25 0x00007ffff7135e9a in start_thread (arg=0x7fffd559f700)

```
at pthread_create.c:308
```
#26 0x00007ffff5881ccd in clone ()

```
at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
```
#27 0x0000000000000000 in ?? ()

### LINKED ISSUE #514: planning_scene_monitor can crash when clearing Octomap due to mutex issue
If the clear Octomap interface is used, there's a thread safety issue which can result in a crash. According to gdb, the PlanningSceneMonitor is calling `clearOctomap()` in one thread, and the PlanningScene is calling `getPlanningSceneMsgOctomap()` in another. `clearOctomap()` is destructing OcTreeNodes, while `getPlanningSceneMsgOctomap()` is writing them. I can't figure out where to correctly lock/unlock the mutex for the octree, however.

### PR DESCRIPTION
**Pull request by jbohren**
fixes #291
fixes #514 

Note that this should unlock things properly in case `getPlanningSceneMsg` throws. It could be useful to clean up stuff elsewhere too.

### CODE REVIEW

**Comment by jbohren** [comment]
This appears to work, going to leave it running all night to be sure.

**Comment by jbohren** [comment]
This has been running for 11 hours without crashing. I think this is good to merge.

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 1]
```diff
@@ -331,7 +335,11 @@ void planning_scene_monitor::PlanningSceneMonitor::scenePublishingThread()
           if (new_scene_update_ == UPDATE_SCENE)
             is_full = true;
           else
+          {
+            occupancy_map_monitor::OccMapTree::ReadLock lock;
+            if (octomap_monitor_) lock = octomap_monitor_->getOcTreePtr()->reading();
```
Comment (davetcoleman) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:340]: Not important, but I dislike this mixed line format and it is also never used else where in MoveIt's code

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 2]
```diff
@@ -344,8 +352,12 @@ void planning_scene_monitor::PlanningSceneMonitor::scenePublishingThread()
             excludeAttachedBodiesFromOctree(); // in case updates have happened to the attached bodies, put them in
             excludeWorldObjectsFromOctree(); // in case updates have happened to the attached bodies, put them in
           }
-          if (is_full)
+          if (is_full) 
+          {
+            occupancy_map_monitor::OccMapTree::ReadLock lock;
+            if (octomap_monitor_) lock = octomap_monitor_->getOcTreePtr()->reading();
```
Comment (davetcoleman) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:358]: Same here

**Comment by davetcoleman** [comment]
Great catch, but I think @isucan should review this

File: planning/planning_scene_monitor/src/planning_scene_monitor.cpp (hunk 1 above)
Comment (jbohren) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:340]: You mean you dislike the single-line `if`?

Comment (jbohren) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:340]: Maybe you'd prefer:

``` cpp
occupancy_map_monitor::OccMapTree::ReadLock lock(octomap_monitor_ ? octomap_monitor_->getOcTreePtr()->reading() : ());
```

Comment (davetcoleman) [inline planning/planning_scene_monitor/src/planning_scene_monitor.cpp:340]: Yea, that's more MoveIt's! style ;-)

**Comment by jbohren** [comment]
Still working without any segfaults.

**Comment by mikeferguson** [comment]
@jbohren This and #555 are similar functionality with different approaches -- is this the preferred instance?

**Comment by jbohren** [comment]
Yeah, this one is preferred because it will release the lock if an exception occurs in the lock scope. Note that I haven't done any performance tests with these locks, though I haven't noticed anything significant, whenever adding more locks to multithreaded code, this might affect it. If there are any benchmarks with perception integrated, I'd suggest they get run before this gets released.

**Comment by mikeferguson** [comment]
I think that given the number of issues people have had with segfaults, a performance hit is a minor problem that can be fixed later should it be discovered. As it was, the existing version was pretty unusable due to segfaults.
